// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDofTd7rSV7NOq8sIAlZuEww_muVwAg7LE',
    appId: '1:604989067023:web:23770f42dd7168d6a1387a',
    messagingSenderId: '604989067023',
    projectId: 'rtc-app-5e83f',
    authDomain: 'rtc-app-5e83f.firebaseapp.com',
    storageBucket: 'rtc-app-5e83f.firebasestorage.app',
    measurementId: 'G-YNLQB3VZER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10zY5UTPN66rPDR4FXjy7niLETOwxg_k',
    appId: '1:604989067023:android:832e54837074fb92a1387a',
    messagingSenderId: '604989067023',
    projectId: 'rtc-app-5e83f',
    storageBucket: 'rtc-app-5e83f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKBUlEQ6oPLwdwe3tGI0RPwZbuu14ANc',
    appId: '1:604989067023:ios:4483091afca90548a1387a',
    messagingSenderId: '604989067023',
    projectId: 'rtc-app-5e83f',
    storageBucket: 'rtc-app-5e83f.firebasestorage.app',
    iosBundleId: 'com.example.rtcMobile',
  );
}
